{%- if pillar.glance.server is defined and pillar.glance.server.get('enabled') %}
{%- from "glance/map.jinja" import monitoring with context %}
{%- set major_threshold = monitoring.endpoint_failed_major_threshold|float %}
{% raw %}
server:
  alert:
    GlanceApiOutage:
      if: >-
        openstack_api_check_status{name="glance"} == 0
      labels:
        severity: critical
        service: glance
      annotations:
        summary: "Glance API outage"
        description: >-
          Glance API is not accessible for the Glance endpoint in the OpenStack service catalog.
    GlareApiOutage:
      if: >-
        openstack_api_check_status{name="glare"} == 0
      labels:
        severity: critical
        service: glance
      annotations:
        summary: "Glare API outage"
        description: >-
          Glare API is not accessible for the Glare endpoint in the OpenStack service catalog.
    GlanceApiEndpointDown:
      if: >-
        http_response_status{name=~"glance.*"} == 0
      for: 2m
      labels:
        severity: minor
        service: glance
      annotations:
        summary: "{{ $labels.name }} endpoint is not accessible"
        description: >-
          The {{ $labels.name }} endpoint on the {{ $labels.host }} node is not accessible for 2 minutes.
{%- endraw %}
    GlanceApiEndpointsDownMajor:
      if: >-
        count(http_response_status{name=~"glance.*"} == 0) by (name) >= count(http_response_status{name=~"glance.*"}) by (name) * {{ major_threshold }}
      for: 2m
      labels:
        severity: major
        service: glance
      annotations:
        summary: "{{major_threshold * 100}}% of {% raw %}{{ $labels.name }} endpoints are not accessible"
        description: >-
          {{ $value }} {{ $labels.name }} endpoints (>= {% endraw %}{{major_threshold * 100}}{% raw %}%) are not accessible for 2 minutes.
    GlanceApiEndpointsOutage:
      if: >-
        count(http_response_status{name=~"glance.*"} == 0) by (name) == count(http_response_status{name=~"glance.*"}) by (name)
      for: 2m
      labels:
        severity: critical
        service: glance
      annotations:
        summary: "{{ $labels.name }} endpoints outage"
        description: >-
          All available {{ $labels.name }} endpoints are not accessible for 2 minutes.
{%- endraw %}
    GlanceErrorLogsTooHigh:
      {%- set log_threshold = monitoring.error_log_rate|float %}
      if: >-
        sum(rate(log_messages{service="glance",level=~"(?i:(error|emergency|fatal))"}[5m])) without (level) > {{ log_threshold }}
{%- raw %}
      labels:
        severity: warning
        service: glance
      annotations:
        summary: "High number of errors in Glance logs"
        description: >-
          The average per-second rate of errors in Glance logs on the {{ $labels.host }} node is {{ $value }} (as measured over the last 5 minutes).
{%- endraw %}
{%- endif %}
